# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_data',
            fields=[
                ('employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=150)),
            ],
        ),
    ]
